.PHONY: install-docker setup-swarm deploy-services start-deploy deploy ls ps

install-docker:
	ansible-playbook -i inventory.yml install_docker.yml

setup-swarm:
	ansible-playbook -i inventory.yml setup_swarm.yml

deploy-services:
	ansible-playbook -i inventory.yml deploy_services.yml

deploy:
	docker stack deploy -c compose.yaml de_stack

start-deploy:
	make install-docker
	make setup-swarm
	make deploy-services